## Role & RoleBinding
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}-backup-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["list", "get", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Chart.Name }}-backup-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Chart.Name }}-backup-secrets
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-backup-secrets
  namespace: {{ .Release.Namespace }}
