apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Chart.Name }}-backup-secrets"
  labels:
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/name: gitlab-backup-secrets
    app.kubernetes.io/component: init-cronjob
spec:
  schedule: "00 09 * * *"  # everyday at 9:00
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Chart.Name }}-backup-secrets
          containers:
          - name: backup-secrets
            image: 255491188216.dkr.ecr.eu-west-3.amazonaws.com/gitlab/backup-secrets:3.20.3
            imagePullPolicy: Always
            command: [ "/bin/bash", "-c", "--" ]
            args:
              - |
                kubectl get secrets gitlab-rails-secret -o json | grep "secrets.yml" | awk '{print $2}' | base64 -d | yq -o=json > secret.json
                aws secretsmanager update-secret --secret-id arn:aws:secretsmanager:eu-west-3:255491188216:secret:service/gitlab-rails-secret-F2CP40 --secret-string file://secret.json
          restartPolicy: Never	  