{{- if .Values.monitoring.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    role: prometheus
  name: gitlab-webservice
spec:
  endpoints:
    - port: http-metrics-ws
  namespaceSelector:
    matchNames:
      - gitlab
  selector:
    matchLabels:
      app: webservice
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    role: prometheus
  name: gitlab-redis-metrics
spec:
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - gitlab
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    role: prometheus
  name: gitlab-kas
spec:
  endpoints:
    - port: http-metrics
  namespaceSelector:
    matchNames:
      - gitlab
  selector:
    matchLabels:
      app: kas
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    role: prometheus
  name: gitlab-exporter
spec:
  endpoints:
    - port: http-metrics
  namespaceSelector:
    matchNames:
      - gitlab
  selector:
    matchLabels:
      app: gitlab-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    role: prometheus
  name: gitlab-gitaly
spec:
  endpoints:
    - port: http-metrics
  namespaceSelector:
    matchNames:
      - gitlab
  selector:
    matchLabels:
      app: gitaly
{{- end }}